version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/medusa-ui"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.springframework.boot:*"
        update-types: ["version-update:semver-major"]  
  - package-ecosystem: "maven"
    directory: "/medusa-showcase"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.springframework.boot:*"
        update-types: ["version-update:semver-major"]  
  - package-ecosystem: 'npm'
    directory: "/medusa-ui/src/main/resources/static"
    schedule:
      interval: "daily"
        
